### ISSUE TITLE
An exception occurs when the library containing Zxing is compiled

### ISSUE THREAD

**Issue by guominfang** [Storyyeller/enjarify#8]
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。

C:\Users\amin>enjarify D:\QcUsers\Win7\Administrator\Desktop\Fordeal.apk -
o D:\QcUsers\Win7\Administrator\Desktop\FORDEAL.jar
1000 classes processed
2000 classes processed
3000 classes processed
4000 classes processed
5000 classes processed
6000 classes processed
7000 classes processed
8000 classes processed
9000 classes processed
Output written to D:\QcUsers\Win7\Administrator\Desktop\FORDEAL.jar
com/google/zxing/aztec/b/d.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

com/google/zxing/common/i.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

com/google/zxing/pdf417/d.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

com/google/zxing/pdf417/decoder/h.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

com/google/zxing/pdf417/encoder/a.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

com/google/zxing/qrcode/a/b.class Traceback (most recent call last):
  File "F:\PythonProjects\enjarify\enjarify\main.py", line 38, in translate
    class_data = writeclass.toClassFile(cls, opts)
  File "F:\PythonProjects\enjarify\enjarify\jvm\writeclass.py", line 122, in toC
lassFile
    pool.write(stream)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 135, in w
rite
    self._writeEntry(stream, item)
  File "F:\PythonProjects\enjarify\enjarify\jvm\constantpool.py", line 104, in _
writeEntry
    stream.u16(len(val))
TypeError: object of type 'NoneType' has no len()

9498 classes translated successfully, 6 classes had errors

C:\Users\amin>

**Comment by Storyyeller** [comment]
Have you confirmed that the relevant classes are valid? 

APKs can contain invalid classes, and Android will not complain as long as the invalid classes are not referenced anyway. Sometimes APKs do this to discourage reverse engineering. It is also possible that the APK was designed for an old version of Android which did not verify bytecode. In order to handle cases like this Enjarify, will just skip the class and report an error, instead of treating invalid classes as fatal errors.

**Comment by guominfang** [comment]
Oh，I see.

Project that might reference the Zxing library, It's compressed when compile it to apk.
